[project]
name = "kvtimedb"
version = "0.1.0"
description = "Simple database storing key,value and timestamp, supportting GET, PUT api calls."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
]
